version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - COURSE_NAME=${COURSE_NAME}
      - VOTING_STUDENTS=${VOTING_STUDENTS}
      - CANDIDATES=${CANDIDATES}
    restart: unless-stopped 